name: Docker Build and Publish

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/meitav_alternate_view

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/cache
          key: ${{ runner.os }}-docker-${{ github.sha }}

  push_image:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.ref == 'refs/tags/*'

    steps:
      - name: Log into Docker registry
        uses: actions/checkout@v4

      - name: Push image
        uses: pusher/dockerfile@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          image: $IMAGE_NAME
          tags:
            - ${{ github.sha }}
            - ${{ env.IMAGE_NAME }}:latest
            - ${{ env.IMAGE_NAME }}:${{ github.ref }}
