name: Update Dependencies

on:
  workflow_dispatch:

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        check-latest: true

    - name: Update dependencies
      id: update_deps
      run: |
        pip install --upgrade pip
        cat requirements.txt | awk -F '~=' '{print $1}' | xargs -n 1 pip index versions 2>/dev/null | awk '/\(.*\)/{pkg=$1} /LATEST:/{print pkg"~="$2}' > new_req.txt
        if ! diff -u requirements.txt new_req.txt; then
          echo "new changes detected"
          mv new_req.txt requirements.txt
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "No changes in requirements.txt. Skipping patch."
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: steps.update_deps.outputs.changes == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -u
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: update dependencies"

    - name: Create new branch
      if: steps.update_deps.outputs.changes == 'true'
      run: |
        git checkout -b update-dependencies-${{ github.run_id }}
        git add .
        git commit -m "chore: update dependencies"
        git push origin update-dependencies-${{ github.run_id }}

    - name: Open Pull Request
      if: steps.update_deps.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: Update dependencies'
        delete-branch: true
        branch: update-dependencies-${{ github.run_id }}
        title: 'chore: Update dependencies'
        body: |
          This pull request updates the dependencies in the requirements.txt file.
          Please review and merge as appropriate.
