name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # runs every Sunday at midnight UTC

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        check-latest: true

    - name: Update dependencies
      run: diff -u requirements.txt <(cat requirements.txt | awk -F '~=' '{print $1}' | xargs pip show | awk '/^Name:/{pkg=$2} /^Version:/{print pkg"~="$2}') | patch -o requirements.txt

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -u
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: update dependencies"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
