name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # runs every Sunday at midnight UTC

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        check-latest: true

    - name: Update dependencies
      id: update_deps
      run: |
        pip install -U -r requirements.txt
        diff_output=$(diff -u requirements.txt <(cat requirements.txt | awk -F '~=' '{print $1}' | xargs pip show | awk '/^Name:/{pkg=$2} /^Version:/{print pkg"~="$2}'))
        if [ -n "$diff_output" ]; then
          echo "$diff_output" | patch --quiet -o requirements.txt
          echo "::set-output name=changes::true"
        else
          echo "No changes in requirements.txt. Skipping patch."
          echo "::set-output name=changes::false"
        fi

    - name: Commit changes
      if: steps.update_deps.outputs.changes == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -u
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: update dependencies"

    - name: Create new branch
      if: steps.update_deps.outputs.changes == 'true'
      run: |
        git checkout -b update-dependencies-${{ github.sha }}
        git add .
        git commit -m "chore: update dependencies"
        git push origin update-dependencies-${{ github.sha }}

    - name: Open Pull Request
      if: steps.update_deps.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: Update dependencies'
        delete-branch: true
        branch: update-dependencies-${{ github.sha }}
        title: 'chore: Update dependencies'
        body: |
          This pull request updates the dependencies in the requirements.txt file.
          Please review and merge as appropriate.
